Cargo.toml, src/multiscalar_mul.rs, src/scalar.rs
Implementation taken from: https://github.com/scipr-lab/zexe/blob/master/algebra-core/src/msm/variable_base.rs and refactored to work with this library.
Makes usage of parallel iterators and only works with `std` feature enabled.
=> Implement var_vase multiscalar multiplication

Cargo.toml, src/lib.rs, src/scalar.rs
Adds Serde support for `Scalar`.
Closes #5
=> Implement serde for `Scalar`

src/g1.rs
=> Implement Serde gor `G1Affine`

src/g2.rs, src/pairings.rs
Currently blocking: https://github.com/dusk-network/plonk/issues/127
- Provides serde support for `G2Affine` and `G2Prepared`.
- Added roundtrip tests for `G2Affine`.
- Added roundtrip tests for `G2Prepared`.
Closes #9 
Closes #10
=> G2Affine & G2Prepared serde implementations

src/g1.rs, src/scalar.rs
This PR is just to change variable declaration so I can use a certain type in PLONK.
=> Dependencies

.github/workflows/dusk_ci.yml, src/lib.rs
See: https://github.com/dusk-network/jubjub/pull/48#discussion_r486971372 which triggered that
=> Remove nightly toolchain spec from nightly workflow

src/fp.rs, src/fp12.rs, src/fp2.rs, src/fp6.rs, src/g1.rs, src/g2.rs
=> Implement/derive Canon for all 'groups' types

CHANGELOG.md, Cargo.toml
=> Canonical v0.5

benches/groups.rs
=> Fix crate benchmarks

Cargo.toml
=> Update to canonical-0.6

CHANGELOG.md, Cargo.toml, benches/groups.rs, src/fp.rs, src/fp12.rs, src/fp2.rs, src/fp6.rs, src/g1.rs, src/g2.rs, src/lib.rs, src/multiscalar_mul.rs, src/pairings.rs, src/scalar.rs, src/tests/mod.rs
Resolves: #51 
Resolves: #60
Resolves: #54
=> Release dusk-bls12_381-0.7

CHANGELOG.md, src/fp.rs, src/fp12.rs, src/fp2.rs, src/fp6.rs, src/g1.rs, src/g2.rs, src/scalar.rs
=> Fix new Canonical version impl

.github/workflows/dusk_ci.yml
=> Add canon feature build & test to CI

CHANGELOG.md, src/scalar.rs
=> Optimize `invert` of `Scalar`

CHANGELOG.md, Cargo.toml, src/fp.rs, src/fp12.rs, src/fp2.rs, src/fp6.rs, src/g1.rs, src/g2.rs, src/lib.rs, src/pairings.rs, src/scalar.rs
=> Add `rkyv` implementation behind feature gate

CHANGELOG.md, src/pairings.rs
=> Remove `Sized` bound on `G2Prepared` `rkyv` impl

CHANGELOG.md
=> Update issue links

CHANGELOG.md, Cargo.toml, README.md
=> Fix `Cargo.toml` categories and doc links

CHANGELOG.md, src/lib.rs, src/scalar.rs
=> Fix GENERATOR

CHANGELOG.md, Cargo.toml
- Fix `no-default-features`
[0.12.2]: https://github.com/dusk-network/bls12_381/compare/v0.12.1...v0.12.2
=> Bump to v0.12.2

CHANGELOG.md, src/scalar/dusk.rs
=> Remove `uni_random` from scalar

CHANGELOG.md, src/fp/dusk.rs, src/g1/dusk.rs, src/g2/dusk.rs, src/scalar/dusk.rs
For https://github.com/dusk-network/bls12_381/issues/148
=> Added `extern crate alloc` declaration in serde modules that use alloc

CHANGELOG.md, src/scalar/dusk.rs
=> Add `to_be_bytes` to `Scalar`

CHANGELOG.md, src/scalar/dusk.rs
=> De-duplicate Serializable for Scalar
