src/lib.rs
src/scalar.rs

Exposes:
- GENERATOR
- ROOT_OF_UNITY
- TWO_ADACITY => `S`

Expose Scalar constants needed by plonk

---

src/lib.rs
src/scalar.rs

- Rename `S` as `TWO_ADACITY` and expose it.
Needed by https://github.com/dusk-network/plonk/pull/152
- Implement `internal_repr` method which returns the internal representation of the `Scalar` reduced as `[u64;4]` so we can use any `Scalar` as an exponent in `pow` fn.
This is needed by  https://github.com/dusk-network/plonk/issues/130 & https://github.com/dusk-network/plonk/issues/131

Expose const and internal_repr getter fn.

---

src/fp.rs
src/fp2.rs
src/fp6.rs
src/multiscalar_mul.rs
src/scalar.rs

- Provides `serde` support for the `Fp`, `Fp2` & `Fp6` data structures.
- Implements tests for each one of them.
Closes #12 and unblocks #10 & #11

Add Serde support for Fp, Fp2 & Fp6

---

Cargo.toml
src/lib.rs
src/scalar.rs

Provided anything that implements `RNG` + `CryptoRng`
the library generates a random `Scalar`.
- We cut down the bytes to just use 254bits of randomness.
On this way the `from_bytes()` method can never fail.

Impl `random` for `Scalar`

---

src/scalar.rs

This feature is needed by some range_proofs that require
a bit_decomposition of the `Scalar` and this aims to
provide this capability.
The bits are expressed in little endian form.
Closes #18

Implement to_bits conversion for `Scalar`

---

Cargo.toml

With this we will be able to transfor `CtOption<T>` into `Option<T>`. 
See: https://github.com/dalek-cryptography/subtle/pull/75

Update subtle dep & bump lib

---

.github/workflows/dusk_ci.yml
CHANGELOG.md
Cargo.toml
src/fp.rs
src/fp2.rs
src/fp6.rs
src/g1.rs
src/g2.rs
src/lib.rs
src/multiscalar_mul.rs
src/pairings.rs
src/scalar.rs

Except for Pippenger's algorithm, the pairing capabilities of the library are `no-std` compliant.
This way, we can declare structures that depend on `G1Affine` (eg PLONK proof)
`serde` was isolated as a feature requirement because it conflicts with the `no-std` environment we need to create.

no-std pairing capability

---

src/g1.rs
src/g2.rs

As per this messages: 
https://github.com/dusk-network/bls12_381/pull/67#pullrequestreview-635549908
https://github.com/dusk-network/bls12_381/pull/67#discussion_r613195938

Remove unnecesary .into()s from Canon impls

---

CHANGELOG.md
Cargo.toml
src/lib.rs

This is necessary since the `Archive` impl for `Vec` is behind the `rkyv/alloc` feature.

Use `rkyv/alloc` on `alloc` feature

---

.github/workflows/dusk_ci.yml
CHANGELOG.md
Cargo.toml
README.md
src/choice.rs
src/fp.rs
src/fp12.rs
src/fp2.rs
src/fp6.rs
src/g1.rs
src/g2.rs
src/scalar.rs

Remove canonical and canonical_derive

---

CHANGELOG.md
Cargo.toml

- Expose `scalar::GENERATOR` constant

Bump to v0.12.1

---

CHANGELOG.md
src/scalar/dusk.rs

Add uniform random scalar generation

---

CHANGELOG.md
Cargo.toml

- Add `uni_random` scalar generation [#125]
- Change `Hash` derive on `Scalar` to explicit implementation [#106]
[0.12.3]: https://github.com/dusk-network/bls12_381/compare/v0.12.2...v0.12.3

Bump to v0.12.3

---

CHANGELOG.md
Cargo.toml
src/scalar/dusk.rs

This commit introduces `from_var_bytes`, a `Scalar` function that will take arbitrary slices, hash with BLAKE2b into 256-bit numbers, and perform a modulus multiplication to produce valid scalars.
Resolves #133

feat: add `from_var_bytes` to `Scalar`

---

CHANGELOG.md
src/scalar/dusk.rs

It now used a 512-bit large destination string to hash into. New name: ~~`from_blake2b`~~ `hash_to_scalar`.
Resolves #137

Refactor and rename `Scalar::from_bytes_wide`

---

Cargo.toml

- Remove `uni_random` from scalar [#135]
- Add `from_var_bytes` to scalar [#133] and refactor and rename to `hash_to_scalar` [#137]

Bump to version 0.13.0-rc.0

---

CHANGELOG.md
Cargo.toml

- Remove `uni_random` from scalar [#135]
- Add `from_var_bytes` to scalar [#133] and refactor and rename to `hash_to_scalar` [#137]
[0.13.0]: https://github.com/dusk-network/bls12_381/compare/v0.12.3...v0.13.0

Bump to v0.13.0

---

CHANGELOG.md
Cargo.toml
src/fp/dusk.rs
src/fp2/dusk.rs
src/fp6/dusk.rs
src/g1/dusk.rs
src/g2/dusk.rs
src/pairings/dusk.rs
src/scalar/dusk.rs

For https://github.com/dusk-network/bls12_381/issues/145.

Change serde implementations

---

CHANGELOG.md
Cargo.toml

- Change serde implementations of `G2Prepared`, `Fp6`, `Fp2`, `Fp`, `G2Affine`, `G1Affine`, `Scalar` [#145]
[0.14.0]: https://github.com/dusk-network/bls12_381/compare/v0.13.0...v0.14.0

Release `0.14.0`

---

CHANGELOG.md
Cargo.toml

- Add `extern crate alloc` declaration in serde modules that use the alloc crate [#148]

Release `0.14.1`
